INSERT INTO Authors VALUES
  (1, 'Stephen', 'King'),
  (2, 'Khaled', 'Hosseini'),
  (3, 'Margaret', 'Mitchell'),
  (4, 'Jack', 'London'),
  (5, 'Leo', 'Tolstoy'),
  (6, 'Fyodor', 'Dostoyevsky');

INSERT INTO BookInventory VALUES
  (DEFAULT, 'The Green Mile', 1, 10),
  (DEFAULT, 'The Kite Runner', 2, 6),
  (DEFAULT, 'Gone with the Wind', 3, 11),
  (DEFAULT, 'Martin Eden', 4, 15),
  (DEFAULT, 'War and Peace', 5, 7),
  (DEFAULT, 'Crime and Punishment', 6, 21);
